### ISSUE TITLE
Error compiling on Debian 9

### ISSUE THREAD

**Issue by geffrix** [R-Vision/winexe-smb2#1]
Hello,

After execute build.sh, I have this error:

---
Checking for program perl                                                         : /usr/bin/perl 
Checking for program perl                                                         : /usr/bin/perl 
Checking for program perl                                                         : /usr/bin/perl 
Checking for perl 5.0.0                                                           : ok 5.24.1 
Checking for perl $Config{vendorprefix}:                                          : '/usr' 
PERL_ARCH_INSTALL_DIR:                                                            : '${LIBDIR}/perl5' 
PERL_LIB_INSTALL_DIR:                                                             : '${DATADIR}/perl5' 
Traceback (most recent call last):
  File "/home/usern/winexe-smb2-master/samba/buildtools/bin/waf", line 76, in <module>
    Scripting.prepare(t, cwd, VERSION, wafdir)
  File "/home/usern/winexe-smb2-master/samba/buildtools/wafadmin/Scripting.py", line 145, in prepare
    prepare_impl(t, cwd, ver, wafdir)
  File "/home/usern/winexe-smb2-master/samba/buildtools/wafadmin/Scripting.py", line 135, in prepare_impl
    main()
  File "wscript", line 349, in main
    wildcard_main(wildcard_cmd)
  File "./buildtools/wafsamba/samba_wildcard.py", line 110, in wildcard_main
    fun(ctx)
  File "/home/usern/winexe-smb2-master/samba/buildtools/wafadmin/Scripting.py", line 241, in configure
    conf.sub_config([''])
  File "/home/usern/winexe-smb2-master/samba/buildtools/wafadmin/Configure.py", line 237, in sub_config
    self.recurse(k, name='configure')
  File "/home/usern/winexe-smb2-master/samba/buildtools/wafadmin/Utils.py", line 634, in recurse
    f(self)
  File "/home/usern/winexe-smb2-master/samba/wscript", line 103, in configure
    conf.SAMBA_CHECK_PERL(mandatory=True)
  File "./buildtools/wafsamba/samba_perl.py", line 59, in SAMBA_CHECK_PERL
    perl_inc.remove('.')
ValueError: list.remove(x): x not in list
Checking for library smb_static                                                    : not found 
Build of static winexe                                                             : disabled 
Cannot continue! Please either install Samba shared libraries and re-run waf, or download the Samba source code and re-run waf with the "--samba-dir" option.
(complete log in /home/usern/winexe-smb2-master/source/build/config.log)

-----
Config.log
-----
# project  configured on Mon Jun 15 18:01:50 2020 by
# waf 1.7.5 (abi 98, python 2070df0 on linux2)
# using ./waf --samba-dir=../samba configure build
#
----------------------------------------
Setting top to
/home/usern/winexe-smb2-master/source
----------------------------------------
Setting out to
/home/usern/winexe-smb2-master/source/build
----------------------------------------
Checking for 'gcc' (c compiler)
find program=['gcc', 'cc'] paths=['/usr/local/bin', '/usr/bin', '/bin', '/usr/local/games', '/usr/games'] var='CC' -> '/usr/bin/gcc'
find program=['ar'] paths=['/usr/local/bin', '/usr/bin', '/bin', '/usr/local/games', '/usr/games'] var='AR' -> '/usr/bin/ar'
/usr/bin/gcc
----------------------------------------------------------------------------------
Checking for program /home/usern/winexe-smb2-master/samba/buildtools/bin/waf
/home/usern/winexe-smb2-master/samba/buildtools/bin/waf
find program=['/home/usern/winexe-smb2-master/samba/buildtools/bin/waf'] paths=['/usr/local/bin', '/usr/bin', '/bin', '/usr/local/games', '/usr/games'] var='/HOME/ADMNETIVORO/WINEXE-SMB2-MASTER/SAMBA/BUILDTOOLS/BIN/WAF' -> '/home/usern/winexe-smb2-master/samba/buildtools/bin/waf'
----------------------------------------------------------------------------------
Checking for library smb_static
==>

int main(int argc, char **argv) {
	return 0;
}

<==
[1/2] c: build/.conf_check_bfa50c7147daab8f569cec95a3bcd112/test.c -> build/.conf_check_bfa50c7147daab8f569cec95a3bcd112/testbuild/test.c.1.o

['/usr/bin/gcc', '../test.c', '-c', '-o', 'test.c.1.o']
[2/2] cprogram: build/.conf_check_bfa50c7147daab8f569cec95a3bcd112/testbuild/test.c.1.o -> build/.conf_check_bfa50c7147daab8f569cec95a3bcd112/testbuild/testprog

['/usr/bin/gcc', 'test.c.1.o', '-o', '/home/usern/winexe-smb2-master/source/build/.conf_check_bfa50c7147daab8f569cec95a3bcd112/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/home/usern/winexe-smb2-master/source/smb_static/build', '-lsmb_static']
err: /usr/bin/ld: cannot find -lsmb_static
collect2: error: ld returned 1 exit status

from /home/usern/winexe-smb2-master/source: Test does not build: Traceback (most recent call last):
  File "/home/usern/winexe-smb2-master/source/.waf-1.7.5-47d5afdb5e7e2856f7f46a7101914026/waflib/Tools/c_config.py", line 451, in run_c_code
    bld.compile()
  File "/home/usern/winexe-smb2-master/source/.waf-1.7.5-47d5afdb5e7e2856f7f46a7101914026/waflib/Build.py", line 198, in compile
    raise Errors.BuildError(self.producer.error)
BuildError: Build failed
 -> task in 'testprog' failed (exit status 1): 
	{task 140054631099856: cprogram test.c.1.o -> testprog}
['/usr/bin/gcc', 'test.c.1.o', '-o', '/home/usern/winexe-smb2-master/source/build/.conf_check_bfa50c7147daab8f569cec95a3bcd112/testbuild/testprog', '-Wl,-Bstatic', '-Wl,-Bdynamic', '-L/home/usern/winexe-smb2-master/source/smb_static/build', '-lsmb_static']

not found
from /home/usern/winexe-smb2-master/source: The configuration failed
----------------------------------------------------------------------------------
Build of static winexe
disabled
from /home/usern/winexe-smb2-master/source: Cannot continue! Please either install Samba shared libraries and re-run waf, or download the Samba source code and re-run waf with the "--samba-dir" option.

**Comment by NetBUG** [comment]
This is a quick guess (I don't have Debian-based machine at hand right now), but seems that `libperl-dev` is missing which is a requirement for Samba

In general, if `configure` fails telling something about missing package, most probably it needs `libpackage-dev` on Debian.

If that does not help, I can check l8r.
